### ISSUE TITLE
SuperCSV fails if the last line is not terminated with a newline (linux)

### ISSUE THREAD

**Issue by rkoshy** [super-csv/super-csv#133]
When using SuperCSV, we encountered a strange error where we would get an IllegalStateException after the last line was processed.

I've isolated this to the case where the last line of the CSV does not have a newline.

Correct behavior should be to return a null

**Comment by rkoshy** [comment]
Stack trace:
```
java.lang.IllegalStateException: Stream already closed
	at org.jvnet.mimepull.DataHead$ReadMultiStream.fetch(DataHead.java:237)
	at org.jvnet.mimepull.DataHead$ReadMultiStream.read(DataHead.java:212)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	at java.io.LineNumberReader.readLine(LineNumberReader.java:199)
	at org.supercsv.io.AbstractTokenizer.readLine(AbstractTokenizer.java:82)
	at org.supercsv.io.Tokenizer.readColumns(Tokenizer.java:101)
	at org.supercsv.io.AbstractCsvReader.readRow(AbstractCsvReader.java:179)
	at org.supercsv.io.CsvBeanReader.readIntoBean(CsvBeanReader.java:249)
	at org.supercsv.io.CsvBeanReader.read(CsvBeanReader.java:190)
```

**Comment by dota17** [comment]
Hi, @rkoshy 
Can  you describe this problem with attachment(e,.g. CSV file code)? I tried on Linux and windows according to your description, but there was no corresponding problem. Thanks!

**Comment by rkoshy** [comment]
I will try to create a standalone test to re-create the issue.

**Comment by dota17** [comment]
Yes, thanks! I am looking forward to it.
