### ISSUE TITLE
Exception Thrown on Special Characters

### ISSUE THREAD

**Issue by DraqueT** [super-csv/super-csv#191]
Under certain scenarios, super-csv will blow up when consuming special characters. To make this error appear:

1) Copy/paste the following CSV data into an empty file:
```
CONLANG, LOCAL
ONE, 1
TWO, 2
THREE, 3
FOURááçõ, 4
```

2) Save this file with encoding: UTF-16 Little Endian

3) Try to parse the file with super-csv

Here is the top stack trace I got while using it:
```
MalformedInputException reading next record: java.nio.charset.MalformedInputException: Input length = 1-java.lang.IllegalStateException
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:352)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:182)
	at org.apache.commons.csv.ExtendedBufferedReader.read(ExtendedBufferedReader.java:58)
	at org.apache.commons.csv.Lexer.nextToken(Lexer.java:95)
	at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:664)
	at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:142)
	at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:155)

```

Let me know if there are any other details I can git to help!

**Comment by DraqueT** [comment]
I just realized that I am an idiot. I am waiting to re-integrate super-csv and making due with the commons parser atm. Disregard.

**Comment by dota17** [comment]
```java
private static void readTest() throws Exception {
	ICsvMapReader mapReader = null;
	try {
		mapReader = new CsvMapReader(new BufferedReader(
			new InputStreamReader(new FileInputStream(ROOT_PATH + "test.csv"), "UTF-16")
		), CsvPreference.STANDARD_PREFERENCE);
		final String[] header = mapReader.getHeader(true);
		final CellProcessor[] processors = new CellProcessor[] {
			new NotNull(),
			new NotNull()
		};
		Map<String, Object> customerMap;
		while( (customerMap = mapReader.read(header, processors)) != null ) {
			System.out.println(String.format("lineNo=%s, rowNo=%s, customerMap=%s", mapReader.getLineNumber(),
				mapReader.getRowNumber(), customerMap));
		}
	}
	finally {
		if ( mapReader != null ){
			mapReader.close();
		}
	}
}
```
output:
```
lineNo=2, rowNo=2, customerMap={ LOCAL= 1, CONLANG=ONE}
lineNo=3, rowNo=3, customerMap={ LOCAL= 2, CONLANG=TWO}
lineNo=4, rowNo=4, customerMap={ LOCAL= 3, CONLANG=THREE}
lineNo=5, rowNo=5, customerMap={ LOCAL= 4, CONLANG=FOURááçõ}
```

```
