### ISSUE TITLE
NoClassDefFoundError occurs in CsvDozerBeanReader

### ISSUE THREAD

**Issue by VinhHungNguyen** [super-csv/super-csv#90]
Hi,
I get this error when I use CsvDozerBeanReader. It seems that the DozerBeanMapper class is missing. I would like to know how to fix it. The crash log is below.
Thanks for your help.

FATAL EXCEPTION: main
                                                                                     Process: com.zappasoft.csvreflectionresearch, PID: 26380
                                                                                     java.lang.NoClassDefFoundError: Failed resolution of: Lorg/dozer/DozerBeanMapper;
                                                                                         at org.supercsv.io.dozer.CsvDozerBeanReader.<init>(CsvDozerBeanReader.java:61)
                                                                                         at com.zappasoft.csvreflectionresearch.SuperCsvWithDozerActivity.readWithCsvDozerBeanReader(SuperCsvWithDozerActivity.java:63)
                                                                                         at com.zappasoft.csvreflectionresearch.SuperCsvWithDozerActivity.onCreate(SuperCsvWithDozerActivity.java:48)
                                                                                         at android.app.Activity.performCreate(Activity.java:5975)
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
                                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "org.dozer.DozerBeanMapper" on path: DexPathList[[zip file "/data/app/com.zappasoft.csvreflectionresearch-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                         at org.supercsv.io.dozer.CsvDozerBeanReader.<init>(CsvDozerBeanReader.java:61) 
                                                                                         at com.zappasoft.csvreflectionresearch.SuperCsvWithDozerActivity.readWithCsvDozerBeanReader(SuperCsvWithDozerActivity.java:63) 
                                                                                         at com.zappasoft.csvreflectionresearch.SuperCsvWithDozerActivity.onCreate(SuperCsvWithDozerActivity.java:48) 
                                                                                         at android.app.Activity.performCreate(Activity.java:5975) 
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269) 
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376) 
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5253) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695) 
                                                                                     	Suppressed: java.lang.ClassNotFoundException: org.dozer.DozerBeanMapper
                                                                                         at java.lang.Class.classForName(Native Method)
                                                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                         		... 17 more
                                                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by ZioberMichal** [comment]
Hi @VinhHungNguyen,
   do you still have a problem with this? You should try to add required library explicitly to your project. I do not know what are you using to build your project but I would like to help you with this error.

**Comment by VinhHungNguyen** [comment]
Hi @ZioberMichal ,
I put the super-csv-2.4.0.jar and super-csv-dozer-2.4.0.jar into the libs folder. I can use the core Super CSV normally. This problem only happens when I use the dozer.

**Comment by ZioberMichal** [comment]
Do you use [Maven](https://maven.apache.org/index.html) or any other project build-and-management tool? Pom for "super-csv-parent" project defines below dependency:
```xml
		<dependency>
			<groupId>net.sf.dozer</groupId>
			<artifactId>dozer</artifactId>
		</dependency>
```
You have to also add this library to your Android project. You can find required jar on this page: http://mvnrepository.com/artifact/net.sf.dozer/dozer

Please let me know whether it works for you.

**Comment by ZioberMichal** [comment]
Hi @VinhHungNguyen, did it help? Can we close this issue?

**Comment by VinhHungNguyen** [comment]
Hi @ZioberMichal ,
Sorry, I was busy. I use Android Studio for the project. I tried adding the dozer-5.x.x.jar to the libs folder, but it does not work.

**Comment by ZioberMichal** [comment]
Strange behaviour. Have you solved it or you still have this problem? If yes please let me know. I also need a full list of libraries related with `Dozer` and `Super CSV` projects.

**Comment by ZioberMichal** [comment]
Mainly this question is not related strictly with project but with building app on Android and looks like solved now.
